### ISSUE TITLE
Biomes sometimes are listed twice at a single location.

### ISSUE THREAD

**Issue by jhprobert** [ebimodeling/ghgvc#43] opened 2014-02-10 16:42 UTC
There are some cases where multiple biomes are available for selection. 
1.  At (37.47, -78.29), there were multiple repeats of temperate pasture, temperate cropland, micanthus, switchgrass, US corn, soybean. 
![multiple biomes 1](https://f.cloud.github.com/assets/6640359/2127703/ee34981a-9271-11e3-934e-10ae2362fadc.png)
2. At (26.43, -80.93), there is a repeat of selections in both the native and the agroecosystem sections.
![multiple biomes 2](https://f.cloud.github.com/assets/6640359/2127722/1a2e12fc-9272-11e3-89e5-8a979bd826bb.png)
3. At (30.79, -85.06), there are repeats in both the native and agroecosystem sections.
![multiple biomes 3](https://f.cloud.github.com/assets/6640359/2127730/45d62836-9272-11e3-814e-078f28cc55fe.png)

**Comment by potterzot** [comment] 2016-07-26 04:33
I can't reproduce this issue. Maybe it's been fixed in other revisions? Closing.

**Closed by potterzot** 2016-07-26 04:33 UTC
