### ISSUE TITLE
test

### ISSUE THREAD

**Issue by hmb1** [ebimodeling/ghgvc#69] opened 2015-08-31 15:09 UTC
I have set up a kind of test harness for checking that any changes  i make to :
 app/controllers/workflows_controller.rb
 Basically I run  my version of the calc on pecandev  thats ( http://www.ecosystemservicescalc.hmb )
 I then pick up the command line parameters that get_biome have been called  with ( ./ghgvc/log/development.log )
 Then  run the following command in a shell script
 
 
curl  --data-urlencode lat=52.64  --data-urlencode lng=-4.0 --data-urlencode id=1  --data-urlencode ecosystems="${ecosystems}" http://www.ecosystemservicescalc.hmb/get_biome

The only problem is that the input "ecosystems" parameter is huge and the returned json file is equally huge
Could be doing something smarter or there a test harness already in place ?

**Comment by dlebauer** [comment] 2016-05-31 20:09
duplicate of #71

**Closed by dlebauer** 2016-05-31 20:09 UTC
